#  Prueba de carga de datos

In [16]:
import sys
sys.path.append("..")  # permite acceder a cargaDatos/, eda/, clases/

In [17]:
from cargaDatos.cargador_datos import CargadorDatos

In [18]:
# Instancia del cargador inteligente
loader = CargadorDatos("../data/raw/premier.csv")

# Cargar datos
df = loader.cargar_csv()

# Mostrar primeras filas
df.head()

 Encoding detectado: utf-8
 Separador detectado: ','
 CARGA DE DATOS REALIZADA
 Archivo: ../data/raw/premier.csv
 Filas cargadas: 4270
 Columnas: 33

 Porcentaje de nulos por columna:
Player                    0.00
Team                      0.00
#                         0.00
Nation                    0.00
Position                  0.00
Age                       0.00
Minutes                   0.14
Goals                     0.00
Assists                   0.00
Penalty Shoot on Goal     0.00
Penalty Shoot             0.00
Total Shoot               0.00
Shoot on Target           0.00
Yellow Cards              0.00
Red Cards                 0.00
Touches                   0.00
Dribbles                  0.00
Tackles                   0.00
Blocks                    0.00
Expected Goals (xG)       0.00
Non-Penalty xG (npxG)     0.00
Expected Assists (xAG)    0.00
Shot-Creating Actions     0.00
Goal-Creating Actions     0.00
Passes Completed          0.00
Passes Attempted          0.00
Pass Completion %         1.08
Progressive Passes        0.00
Carries                   0.00
Progressive Carries       0.00
Dribble Attempts          0.00
Successful Dribbles       0.00
Date                      0.00
dtype: float64

 Nulos totales: 52 de 140910 celdas
 Porcentaje total de nulos: 0.04%

,Player,Team,#,Nation,Position,Age,Minutes,Goals,Assists,Penalty Shoot on Goal,...,Goal-Creating Actions,Passes Completed,Passes Attempted,Pass Completion %,Progressive Passes,Carries,Progressive Carries,Dribble Attempts,Successful Dribbles,Date
0,Bruno Fernandes,Manchester United,8,POR,"FW,AM",29-343,90.0,0,0,0,...,0,43,60,"71,7",6,50,7,1,1,2024-08-16
1,Marcus Rashford,Manchester United,10,ENG,LW,26-290,90.0,0,0,0,...,0,22,30,"73,3",2,34,2,6,0,2024-08-16
2,Amad Diallo,Manchester United,16,CIV,RW,22-036,NaN,0,0,0,...,0,28,33,"84,8",1,22,0,1,1,2024-08-16
3,Alejandro Garnacho,Manchester United,17,ARG,RW,20-046,30.0,0,1,0,...,1,10,11,"90,9",0,11,2,2,0,2024-08-16
4,Mason Mount,Manchester United,7,ENG,AM,25-219,60.0,0,0,0,...,0,11,15,"73,3",1,16,0,2,0,2024-08-16

In [19]:
df.shape

(4270, 33)

In [20]:
df.dtypes

Player                     object
Team                       object
#                           int64
Nation                     object
Position                   object
Age                        object
Minutes                   float64
Goals                       int64
Assists                     int64
Penalty Shoot on Goal       int64
Penalty Shoot               int64
Total Shoot                 int64
Shoot on Target             int64
Yellow Cards                int64
Red Cards                   int64
Touches                     int64
Dribbles                    int64
Tackles                     int64
Blocks                      int64
Expected Goals (xG)       float64
Non-Penalty xG (npxG)     float64
Expected Assists (xAG)    float64
Shot-Creating Actions       int64
Goal-Creating Actions       int64
Passes Completed            int64
Passes Attempted            int64
Pass Completion %          object
Progressive Passes          int64
Carries                     int64
Progressive Carries         int64
Dribble Attempts            int64
Successful Dribbles         int64
Date                       object
dtype: object

In [21]:
df.isnull().sum().sum()

np.int64(52)

In [22]:
(df.isnull().mean() * 100).round(2)

Player                    0.00
Team                      0.00
#                         0.00
Nation                    0.00
Position                  0.00
Age                       0.00
Minutes                   0.14
Goals                     0.00
Assists                   0.00
Penalty Shoot on Goal     0.00
Penalty Shoot             0.00
Total Shoot               0.00
Shoot on Target           0.00
Yellow Cards              0.00
Red Cards                 0.00
Touches                   0.00
Dribbles                  0.00
Tackles                   0.00
Blocks                    0.00
Expected Goals (xG)       0.00
Non-Penalty xG (npxG)     0.00
Expected Assists (xAG)    0.00
Shot-Creating Actions     0.00
Goal-Creating Actions     0.00
Passes Completed          0.00
Passes Attempted          0.00
Pass Completion %         1.08
Progressive Passes        0.00
Carries                   0.00
Progressive Carries       0.00
Dribble Attempts          0.00
Successful Dribbles       0.00
Date                      0.00
dtype: float64

In [23]:
df.describe(include="all")

,Player,Team,#,Nation,Position,Age,Minutes,Goals,Assists,Penalty Shoot on Goal,...,Goal-Creating Actions,Passes Completed,Passes Attempted,Pass Completion %,Progressive Passes,Carries,Progressive Carries,Dribble Attempts,Successful Dribbles,Date
count,4270,4270,4270.000000,4270,4270,4270,4264.000000,4270.000000,4270.000000,4270.000000,...,4270.000000,4270.000000,4270.000000,4224,4270.000000,4270.000000,4270.000000,4270.000000,4270.000000,4270
unique,478,20,NaN,57,164,2942,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,402,NaN,NaN,NaN,NaN,NaN,37
top,Joshua Zirkzee,Fulham,NaN,ENG,CB,22-188,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"100,0",NaN,NaN,NaN,NaN,NaN,2024-09-14
freq,14,222,NaN,1273,653,6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,262,NaN,NaN,NaN,NaN,NaN,250
mean,NaN,NaN,16.780094,NaN,NaN,NaN,64.791510,0.094145,0.071194,0.005855,...,0.166276,26.152927,32.061593,NaN,2.456206,22.330445,1.236300,1.215925,0.533255,NaN
std,NaN,NaN,12.215586,NaN,NaN,NaN,31.249166,0.326883,0.271362,0.085014,...,0.458118,20.604004,22.945436,NaN,2.745780,16.012547,1.760593,1.742428,0.963710,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,NaN,NaN,8.000000,NaN,NaN,NaN,34.000000,0.000000,0.000000,0.000000,...,0.000000,9.000000,13.000000,NaN,0.000000,10.000000,0.000000,0.000000,0.000000,NaN
50%,NaN,NaN,15.000000,NaN,NaN,NaN,82.500000,0.000000,0.000000,0.000000,...,0.000000,22.000000,29.000000,NaN,2.000000,20.000000,1.000000,1.000000,0.000000,NaN
75%,NaN,NaN,24.000000,NaN,NaN,NaN,90.000000,0.000000,0.000000,0.000000,...,0.000000,38.000000,46.000000,NaN,4.000000,31.000000,2.000000,2.000000,1.000000,NaN
max,NaN,NaN,87.000000,NaN,NaN,NaN,90.000000,4.000000,3.000000,3.000000,...,6.000000,127.000000,140.000000,NaN,30.000000,106.000000,18.000000,16.000000,12.000000,NaN